# Generated by Django 4.2.8 on 2024-02-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="用户账号",
                        max_length=100,
                        unique=True,
                        verbose_name="用户账号",
                    ),
                ),
                (
                    "userpwd",
                    models.CharField(
                        help_text="用户密码", max_length=64, verbose_name="用户密码"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="真实姓名", max_length=40, verbose_name="姓名"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "未知"), (1, "男"), (2, "女")],
                        default=0,
                        help_text="性别",
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="手机号码",
                        max_length=11,
                        null=True,
                        verbose_name="手机号码",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="邮箱",
                        max_length=255,
                        null=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="头像"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
                "ordering": ["id"],
            },
        ),
    ]
