# Generated by Django 4.2.8 on 2024-02-15 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_goods_inventory_role_salereceipt_stockorder_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_pwd",
            new_name="password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="true_name",
        ),
    ]
