# Generated by Django 4.2.8 on 2024-02-28 14:38

import apps.system.utils.create_uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0003_rename_user_pwd_user_password_remove_user_true_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=apps.system.utils.create_uuid.UUIDTools.uuid4_hex,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
