# Generated by Django 4.2.8 on 2024-02-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
