# Generated by Django 4.2.8 on 2024-02-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
