# Generated by Django 4.2.8 on 2024-02-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system",
            "0007_alter_user_managers_user_date_joined_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
