# Generated by Django 4.2.8 on 2024-02-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text="用户密码", max_length=64, verbose_name="用户密码"
            ),
        ),
    ]
