# Generated by Django 4.2.8 on 2024-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
