# Generated by Django 4.2.8 on 2024-03-02 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goods",
            old_name="bread_name",
            new_name="breadname",
        ),
    ]
