# Generated by Django 4.2.8 on 2024-03-04 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_rename_bread_name_goods_breadname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goods",
            old_name="shelf_life",
            new_name="sheld_life",
        ),
    ]
