# Generated by Django 4.2.8 on 2024-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0012_rename_shelf_life_goods_sheld_life"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="真实姓名",
                max_length=64,
                null=True,
                verbose_name="真实姓名",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="用户名",
                max_length=100,
                unique=True,
                verbose_name="用户名",
            ),
        ),
    ]
