# Generated by Django 4.2.8 on 2024-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0013_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(
                blank=True, help_text="角色", to="system.role", verbose_name="角色"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True, help_text="头像", max_length=100, null=True, verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True, help_text="生日", null=True, verbose_name="生日"
            ),
        ),
    ]
