# Generated by Django 4.2.8 on 2024-03-12 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0014_user_role_alter_user_avatar_alter_user_birthday"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
