# Generated by Django 4.2.8 on 2024-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0015_delete_userrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(
                blank=True,
                help_text="角色",
                related_name="users",
                to="system.role",
                verbose_name="角色",
            ),
        ),
    ]
