# Generated by Django 4.2.8 on 2024-03-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0017_permission_role_permission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="parent",
        ),
        migrations.AddField(
            model_name="permission",
            name="pid",
            field=models.ForeignKey(
                blank=True,
                help_text="父权限id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="system.permission",
                verbose_name="父权限id",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="level",
            field=models.IntegerField(
                blank=True, help_text="权限等级", null=True, verbose_name="权限等级"
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="select",
            field=models.BooleanField(
                default=False, help_text="是否选中", verbose_name="是否选中"
            ),
        ),
    ]
