# Generated by Django 4.2.8 on 2024-03-15 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0018_remove_permission_parent_permission_pid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="select",
        ),
    ]
