# Generated by Django 4.2.8 on 2024-03-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0019_remove_permission_select"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="code",
            field=models.CharField(
                help_text="权限值", max_length=100, null=True, verbose_name="权限值"
            ),
        ),
    ]
