# Generated by Django 4.2.8 on 2024-03-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0020_permission_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                help_text="权限值",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="权限值",
            ),
        ),
    ]
