# Generated by Django 4.2.8 on 2024-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0021_alter_permission_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="is_button",
            field=models.BooleanField(
                help_text="是否为按钮", null=True, verbose_name="是否为按钮"
            ),
        ),
    ]
