# Generated by Django 4.2.8 on 2024-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0022_permission_is_button"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="is_button",
            field=models.BooleanField(
                default=0, help_text="是否为按钮", verbose_name="是否为按钮"
            ),
            preserve_default=False,
        ),
    ]
