# Generated by Django 4.2.8 on 2024-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0023_alter_permission_is_button"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="bread_name",
        ),
        migrations.AddField(
            model_name="inventory",
            name="breadname",
            field=models.CharField(
                help_text="面包名称", max_length=64, null=True, verbose_name="面包名称"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="MFG_date",
            field=models.DateField(help_text="生产日期", null=True, verbose_name="生产日期"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="单价",
                max_digits=10,
                null=True,
                verbose_name="单价",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="sale_count",
            field=models.IntegerField(help_text="出库数量", null=True, verbose_name="出库数量"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="shelf_life",
            field=models.IntegerField(
                help_text="保质期（天）", null=True, verbose_name="保质期（天）"
            ),
        ),
    ]
