# Generated by Django 4.2.8 on 2024-03-28 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0024_remove_inventory_bread_name_inventory_breadname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="shelf_life",
            new_name="shield_life",
        ),
    ]
