# Generated by Django 4.2.8 on 2024-03-28 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0025_rename_shelf_life_inventory_shield_life"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goods",
            old_name="sheld_life",
            new_name="shield_life",
        ),
    ]
