# Generated by Django 4.2.8 on 2024-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0026_rename_sheld_life_goods_shield_life"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="sale_count",
            new_name="out_count",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="进价",
                max_digits=10,
                null=True,
                verbose_name="进价",
            ),
        ),
    ]
