# Generated by Django 4.2.8 on 2024-03-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0027_rename_sale_count_inventory_out_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="receipt",
            field=models.ForeignKey(
                help_text="销售单",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_items",
                to="system.salereceipt",
                verbose_name="销售单",
            ),
        ),
    ]
