# Generated by Django 4.2.8 on 2024-03-29 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0028_alter_receiptitem_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="receipt",
            field=models.ForeignKey(
                help_text="销售单",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detail",
                to="system.salereceipt",
                verbose_name="销售单",
            ),
        ),
    ]
