# Generated by Django 4.2.8 on 2024-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0029_alter_receiptitem_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, help_text="邮箱", max_length=50, null=True, verbose_name="邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="用户名",
                max_length=30,
                unique=True,
                verbose_name="用户名",
            ),
        ),
    ]
