# Generated by Django 4.2.8 on 2024-05-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0030_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                help_text="权限值",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="权限值",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(
                help_text="权限名称", max_length=30, unique=True, verbose_name="权限名称"
            ),
        ),
    ]
