# Generated by Django 4.2.8 on 2024-05-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0031_alter_permission_code_alter_permission_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favatar",
            field=models.ImageField(
                blank=True,
                help_text="头像",
                max_length=255,
                null=True,
                upload_to="favatar",
                verbose_name="头像",
            ),
        ),
    ]
