# Generated by Django 4.2.8 on 2024-05-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0032_user_favatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favatar",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="头像",
                max_length=255,
                null=True,
                upload_to="favatar",
                verbose_name="头像",
            ),
        ),
    ]
