# Generated by Django 4.2.8 on 2024-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0033_remove_user_favatar_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="头像",
                max_length=255,
                null=True,
                upload_to="avatar",
                verbose_name="头像",
            ),
        ),
    ]
