# Generated by Django 4.2.8 on 2024-05-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0035_customer_salereceipt_customer"),
    ]

    operations = [

        migrations.AddField(
            model_name="inventory",
            name="goods",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory",
                to="system.goods",
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="breadname",
            field=models.CharField(
                help_text="面包名称", max_length=64, verbose_name="面包名称"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="MFG_date",
            field=models.DateField(help_text="生产日期", verbose_name="生产日期"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="breadname",
            field=models.CharField(
                help_text="面包名称", max_length=64, verbose_name="面包名称"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="out_count",
            field=models.IntegerField(default=0, help_text="出库数量", verbose_name="出库数量"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="进价", max_digits=10, verbose_name="进价"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="shield_life",
            field=models.IntegerField(help_text="保质期（天）", verbose_name="保质期（天）"),
        ),
    ]
