# Generated by Django 4.2.8 on 2024-05-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0038_customerlevel_delete_stockorder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiptitem",
            name="bread",
        ),
    ]
