# Generated by Django 4.2.8 on 2024-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0040_customerlevel_delete_stockorder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        db_index=True,
                        help_text="会员等级",
                        unique=True,
                        verbose_name="会员等级",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="优惠折扣",
                        max_digits=10,
                        verbose_name="优惠折扣",
                    ),
                ),
                (
                    "required_score",
                    models.IntegerField(
                        default=0, help_text="所需积分", verbose_name="所需积分"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatabaseBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_name",
                    models.CharField(max_length=255, unique=True, verbose_name="备份名字"),
                ),
                (
                    "backup_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="备份时间"),
                ),
                (
                    "backup_description",
                    models.TextField(blank=True, verbose_name="备份描述"),
                ),
                (
                    "backup_file",
                    models.FileField(upload_to="backups/", verbose_name="备份文件"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StockOrder",
        ),
    ]
